//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crims.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class crims_users
    {
        public int TableId { get; set; }
        public string UserName { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int Status { get; set; }
    }
}
