//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crims.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class crims_custom_fields
    {
        public int TableId { get; set; }
        public string CustomFieldId { get; set; }
        public string CustomFieldName { get; set; }
        public string CustomFieldSize { get; set; }
        public string CustomListId { get; set; }
        public string CustomGroupId { get; set; }
        public int FieldTypeId { get; set; }
        public int TabIndex { get; set; }
        public int Required { get; set; }
    }
}
