//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crims.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class crims_custom_field_types
    {
        public int TableId { get; set; }
        public string FieldTypeId { get; set; }
        public string FieldTypeName { get; set; }
    }
}
