//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crims.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class crims_base_data
    {
        public int TableId { get; set; }
        public string ProjectCode { get; set; }
        public int EnrollmentId { get; set; }
        public string Surname { get; set; }
        public string Firstname { get; set; }
        public string MiddleName { get; set; }
        public string Gender { get; set; }
        public string Title { get; set; }
        public string Email { get; set; }
        public string MobileNumber { get; set; }
        public string CuntryCode { get; set; }
        public string ProjectPrimaryCode { get; set; }
        public string DOB { get; set; }
        public System.DateTime EnrollmentDate { get; set; }
        public string ValidIdNumber { get; set; }
    }
}
